version: '3'

services:
  registry:
    image: registry:2
    container_name: hub.local
    restart: always
    ports:
    - "5000:5000"
    volumes:
    - D:\localhub\registry:/var/lib/registry #windows os
  docker-registry-ui:
    image: konradkleine/docker-registry-frontend
    container_name: docker-registry-ui
    restart: always
    ports:
    - "7000:80"
    environment:
      ENV_DOCKER_REGISTRY_HOST: hub.local
      ENV_DOCKER_REGISTRY_PORT: 5000
